### PR TITLE
Undo massive clobbering of history and code

### PR DESCRIPTION
**Pull request by ketch**
This PR reintroduces all the changes that were erased by someone recently.

### CODE REVIEW

**Comment by mcr222** [comment]
Oh! That was me sorry! I think Eclipse did the --force for me.... I was just trying to add images, that's why I skipped branching and doing a PR.

**Comment by ketch** [comment]
I would strongly advise against continuing to use any software that helped you to erase a month of your collaborators' work.  But in any case it won't be possible for it to happen again with this repo.

**Comment by ketch** [comment]
The unfortunate effect that will never be fixed is the destruction of the actual history.

**Comment by mcr222** [comment]
Well, it is more of my fault than Eclipse's. I will be more careful next time. Thanks and sorry!

**Pull request merged**
